-- H2 2.2.220; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '250be59c3825d2c7' HASH '8573288e188592815f10ed715ecd4ded5e1cbf4a5a9b470767ece9529c646dfc' ADMIN;          
CREATE CACHED TABLE "PUBLIC"."flyway_schema_history"(
    "installed_rank" INTEGER NOT NULL,
    "version" CHARACTER VARYING(50),
    "description" CHARACTER VARYING(200) NOT NULL,
    "type" CHARACTER VARYING(20) NOT NULL,
    "script" CHARACTER VARYING(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" CHARACTER VARYING(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
);           
ALTER TABLE "PUBLIC"."flyway_schema_history" ADD CONSTRAINT "PUBLIC"."flyway_schema_history_pk" PRIMARY KEY("installed_rank"); 
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.flyway_schema_history;    
INSERT INTO "PUBLIC"."flyway_schema_history" VALUES
(-1, NULL, '<< Flyway Schema History table created >>', 'TABLE', '', NULL, 'SA', TIMESTAMP '2024-04-03 22:53:47.59239', 0, TRUE),
(1, '1', '<< Flyway Baseline >>', 'BASELINE', '<< Flyway Baseline >>', NULL, 'SA', TIMESTAMP '2024-04-03 22:53:47.607344', 0, TRUE);     
CREATE INDEX "PUBLIC"."flyway_schema_history_s_idx" ON "PUBLIC"."flyway_schema_history"("success" NULLS FIRST);
CREATE CACHED TABLE "PUBLIC"."FILTER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 6) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL
);   
ALTER TABLE "PUBLIC"."FILTER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");        
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.FILTER;   
INSERT INTO "PUBLIC"."FILTER" VALUES
(1, 'High Rated Movies'),
(2, 'second filter'),
(3, 'Complex Movie Filter'),
(4, 'A filter'),
(5, 'test filter');         
CREATE CACHED TABLE "PUBLIC"."CRITERION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 10) NOT NULL,
    "FILTER_ID" BIGINT,
    "FIELD_NAME" CHARACTER VARYING(255) NOT NULL,
    "CRITERIA_TYPE" CHARACTER VARYING(255) NOT NULL,
    "COMPARISON_OPERATOR" CHARACTER VARYING(255) NOT NULL,
    "CRITERIA_VALUE" CHARACTER VARYING(255) NOT NULL
);           
ALTER TABLE "PUBLIC"."CRITERION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");     
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.CRITERION;
INSERT INTO "PUBLIC"."CRITERION" VALUES
(1, 1, 'voteAverage', 'numeric', '>', '7.5'),
(2, 2, 'voteAverage', 'numeric', '<', '5.5'),
(3, 3, 'title', 'string', 'contains', 'a'),
(4, 3, 'popularity', 'numeric', '>', '11'),
(5, 3, 'voteAverage', 'numeric', '>', '3'),
(6, 3, 'originalTitle', 'string', 'contains', 'man'),
(7, 3, 'releaseDate', 'date', '>', '2015-01-01'),
(8, 4, 'title', 'string', 'startsWith', 'a'),
(9, 5, 'title', 'string', 'startsWith', 'a');    
CREATE CACHED TABLE "PUBLIC"."MOVIE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 31) NOT NULL,
    "ORIGINAL_TITLE" CHARACTER VARYING(86) NOT NULL,
    "OVERVIEW" CHARACTER VARYING(1000) NOT NULL,
    "POPULARITY" NUMERIC(38, 2) NOT NULL,
    "RELEASE_DATE" DATE NOT NULL,
    "REVENUE" BIGINT NOT NULL,
    "RUNTIME" NUMERIC(38, 2) NOT NULL,
    "TAGLINE" CHARACTER VARYING(252),
    "TITLE" CHARACTER VARYING(86) NOT NULL,
    "VOTE_AVERAGE" NUMERIC(38, 2) NOT NULL,
    "VOTE_COUNT" INTEGER NOT NULL
);      
ALTER TABLE "PUBLIC"."MOVIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 30 +/- SELECT COUNT(*) FROM PUBLIC.MOVIE;   
INSERT INTO "PUBLIC"."MOVIE" VALUES
(1, 'Avatar', 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.', 150.44, DATE '2009-12-10', 2787965087, 162.00, 'Enter the World of Pandora.', 'Avatar', 7.20, 11800),
(2, 'Pirates of the Caribbean: At World''s End', 'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.', 139.08, DATE '2007-05-19', 961000000, 169.00, 'At the end of the world, the adventure begins.', 'Pirates of the Caribbean: At World''s End', 6.90, 4500),
(3, 'Spectre', U&'A cryptic message from Bond\2019s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.', 107.38, DATE '2015-10-26', 880674609, 148.00, 'A Plan No One Escapes', 'Spectre', 6.30, 4466),
(4, 'The Dark Knight Rises', 'Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent''s crimes to protect the late attorney''s reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham''s finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.', 112.31, DATE '2012-07-16', 1084939099, 165.00, 'The Legend Ends', 'The Dark Knight Rises', 7.60, 9106),
(5, 'John Carter', 'John Carter is a war-weary, former military captain who''s inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It''s a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands.', 43.93, DATE '2012-03-07', 284139100, 132.00, 'Lost in our world, found in another.', 'John Carter', 6.10, 2124),
(6, 'Spider-Man 3', U&'The seemingly invincible Spider-Man goes up against an all-new crop of villain \2013 including the shape-shifting Sandman. While Spider-Man\2019s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.', 115.70, DATE '2007-05-01', 890871626, 139.00, 'The battle within.', 'Spider-Man 3', 5.90, 3576),
(7, 'Tangled', 'When the kingdom''s most wanted-and most charming-bandit Flynn Rider hides out in a mysterious tower, he''s taken hostage by Rapunzel, a beautiful and feisty tower-bound teen with 70 feet of magical, golden hair. Flynn''s curious captor, who''s looking for her ticket out of the tower where she''s been locked away for years, strikes a deal with the handsome thief and the unlikely duo sets off on an action-packed escapade, complete with a super-cop horse, an over-protective chameleon and a gruff gang of pub thugs.', 48.68, DATE '2010-11-24', 591794936, 100.00, 'They''re taking adventure to new lengths.', 'Tangled', 7.40, 3330),
(8, 'Avengers: Age of Ultron', U&'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth\2019s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.', 134.28, DATE '2015-04-22', 1405403694, 141.00, 'A New Age Has Come.', 'Avengers: Age of Ultron', 7.30, 6767),
(9, 'Harry Potter and the Half-Blood Prince', 'As Harry begins his sixth year at Hogwarts, he discovers an old book marked as ''Property of the Half-Blood Prince'', and begins to learn more about Lord Voldemort''s dark past.', 98.89, DATE '2009-07-07', 933959197, 153.00, 'Dark Secrets Revealed', 'Harry Potter and the Half-Blood Prince', 7.40, 5293),
(10, 'Batman v Superman: Dawn of Justice', U&'Fearing the actions of a god-like Super Hero left unchecked, Gotham City\2019s own formidable, forceful vigilante takes on Metropolis\2019s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it\2019s ever known before.', 155.79, DATE '2016-03-23', 873260194, 151.00, 'Justice or revenge', 'Batman v Superman: Dawn of Justice', 5.70, 7004);              
INSERT INTO "PUBLIC"."MOVIE" VALUES
(11, 'Superman Returns', 'Superman returns to discover his 5-year absence has allowed Lex Luthor to walk free, and that those he was closest too felt abandoned and have moved on. Luthor plots his ultimate revenge that could see millions killed and change the face of the planet forever, as well as ridding himself of the Man of Steel.', 57.93, DATE '2006-06-28', 391081192, 154.00, NULL, 'Superman Returns', 5.40, 1400),
(12, 'Quantum of Solace', 'Quantum of Solace continues the adventures of James Bond after Casino Royale. Betrayed by Vesper, the woman he loved, 007 fights the urge to make his latest mission personal. Pursuing his determination to uncover the truth, Bond and M interrogate Mr. White, who reveals that the organization that blackmailed Vesper is far more complex and dangerous than anyone had imagined.', 107.93, DATE '2008-10-30', 586090727, 106.00, 'For love, for hate, for justice, for revenge.', 'Quantum of Solace', 6.10, 2965),
(13, 'Pirates of the Caribbean: Dead Man''s Chest', 'Captain Jack Sparrow works his way out of a blood debt with the ghostly Davey Jones, he also attempts to avoid eternal damnation.', 145.85, DATE '2006-06-20', 1065659812, 151.00, 'Jack is back!', 'Pirates of the Caribbean: Dead Man''s Chest', 7.00, 5246),
(14, 'The Lone Ranger', 'The Texas Rangers chase down a gang of outlaws led by Butch Cavendish, but the gang ambushes the Rangers, seemingly killing them all. One survivor is found, however, by an American Indian named Tonto, who nurses him back to health. The Ranger, donning a mask and riding a white stallion named Silver, teams up with Tonto to bring the unscrupulous gang and others of that ilk to justice.', 49.05, DATE '2013-07-03', 89289910, 149.00, 'Never Take Off the Mask', 'The Lone Ranger', 5.90, 2311),
(15, 'Man of Steel', 'A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.', 99.40, DATE '2013-06-12', 662845518, 143.00, 'You will believe that a man can fly.', 'Man of Steel', 6.50, 6359),
(16, 'The Chronicles of Narnia: Prince Caspian', 'One year after their incredible adventures in the Lion, the Witch and the Wardrobe, Peter, Edmund, Lucy and Susan Pevensie return to Narnia to aid a young prince whose life has been threatened by the evil King Miraz. Now, with the help of a colorful cast of new characters, including Trufflehunter the badger and Nikabrik the dwarf, the Pevensie clan embarks on an incredible quest to ensure that Narnia is returned to its rightful heir.', 53.98, DATE '2008-05-15', 419651413, 150.00, 'Hope has a new face.', 'The Chronicles of Narnia: Prince Caspian', 6.30, 1630),
(17, 'The Avengers', 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!', 144.45, DATE '2012-04-25', 1519557910, 143.00, 'Some assembly required.', 'The Avengers', 7.40, 11776),
(18, 'Pirates of the Caribbean: On Stranger Tides', 'Captain Jack Sparrow crosses paths with a woman from his past, and he''s not sure if it''s love -- or if she''s a ruthless con artist who''s using him to find the fabled Fountain of Youth. When she forces him aboard the Queen Anne''s Revenge, the ship of the formidable pirate Blackbeard, Jack finds himself on an unexpected adventure in which he doesn''t know who to fear more: Blackbeard or the woman from his past.', 135.41, DATE '2011-05-14', 1045713802, 136.00, 'Live Forever Or Die Trying.', 'Pirates of the Caribbean: On Stranger Tides', 6.40, 4948),
(19, 'Men in Black 3', 'Agents J (Will Smith) and K (Tommy Lee Jones) are back...in time. J has seen some inexplicable things in his 15 years with the Men in Black, but nothing, not even aliens, perplexes him as much as his wry, reticent partner. But when K''s life and the fate of the planet are put at stake, Agent J will have to travel back in time to put things right. J discovers that there are secrets to the universe that K never told him - secrets that will reveal themselves as he teams up with the young Agent K (Josh Brolin) to save his partner, the agency, and the future of humankind.', 52.04, DATE '2012-05-23', 624026776, 106.00, 'They are back... in time.', 'Men in Black 3', 6.20, 4160); 
INSERT INTO "PUBLIC"."MOVIE" VALUES
(20, 'The Hobbit: The Battle of the Five Armies', 'Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor''s mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo''s hands.', 120.97, DATE '2014-12-10', 956019788, 144.00, 'Witness the defining chapter of the Middle-Earth saga', 'The Hobbit: The Battle of the Five Armies', 7.10, 4760),
(21, 'The Amazing Spider-Man', U&'Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents'' disappearance \2013 leading him directly to Oscorp and the lab of Dr. Curt Connors, his father''s former partner. As Spider-Man is set on a collision course with Connors'' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.', 89.87, DATE '2012-06-27', 752215857, 136.00, 'The untold story begins.', 'The Amazing Spider-Man', 6.50, 6586),
(22, 'Raising Victor Vargas', 'The film follows Victor, a Lower East Side teenager, as he deals with his eccentric family, including his strict grandmother, his bratty sister, and a younger brother who completely idolizes him. Along the way he tries to win the affections of Judy, who is very careful and calculating when it comes to how she deals with men.', 3.64, DATE '2002-05-16', 2816116, 88.00, NULL, 'Raising Victor Vargas', 7.80, 13),
(23, U&'Die B\00fcchse der Pandora', 'The rise and inevitable fall of an amoral but naive young woman whose insouciant eroticism inspires lust and violence in those around her.', 1.82, DATE '1929-01-30', 0, 109.00, NULL, 'Pandora''s Box', 7.60, 45),
(24, 'Harrison Montgomery', 'Film from Daniel Davila', 0.01, DATE '2008-01-01', 0, 0.00, NULL, 'Harrison Montgomery', 0.00, 0),
(25, 'Cama adentro', 'Buenos Aires is in a deep recession. As the money runs out, the relationship between an employer and her live-in maid changes dramatically.', 0.04, DATE '2004-09-21', 0, 83.00, NULL, 'Live-In Maid', 7.80, 3),
(26, 'Deterrence', 'The President of the United States must deal with an international military crisis while confined to a Colorado diner during a freak snowstorm.', 2.17, DATE '2000-03-10', 0, 101.00, NULL, 'Deterrence', 6.10, 7),
(27, 'The Mudge Boy', 'Duncan Mudge, mid-teens, lives apart from his rural world populated by his distant father and rough local kids. His main companionship is a chicken left after his mother''s death until the neighbor''s son befriends him.', 5.29, DATE '2003-01-17', 62852, 94.00, NULL, 'The Mudge Boy', 7.30, 23),
(28, 'The Young Unknowns', 'Charlie, his sexy girlfriend, and his moronic best friend drink, drug, and self-destruct over the course of one day at Charlie''s father home in Los Angeles.', 0.00, DATE '2000-03-12', 0, 87.00, NULL, 'The Young Unknowns', 0.00, 0),
(29, 'Not Cool', 'NOT COOL follows former prom king and college freshman Scott (Shane Dawson) who has just returned home for Thanksgiving break only to be dumped by his eccentric, long-term girlfriend. With his world turned upside down, Scott strikes an unlikely friendship with former classmate Tori (Cherami Leigh), an ugly duckling who blossomed in her first semester of college. Together, the two embark on an outrageous adventure through their hometown. But when Scott and Tori find their friendship turning into something deeper, they realize that a few months away may have changed them more than they realized.', 1.19, DATE '2014-09-23', 0, 90.00, NULL, 'Not Cool', 3.70, 25),
(30, U&'D\00f8d sn\00f8', 'Eight medical students on a ski trip to Norway discover that Hitler''s horrors live on when they come face to face with a battalion of zombie Nazi soldiers intent on devouring anyone unfortunate enough to wander into the remote mountains where they were once sent to die.', 11.21, DATE '2009-01-09', 1984662, 91.00, 'Eins, Zwei, Die!', 'Dead Snow', 6.10, 311);   
ALTER TABLE "PUBLIC"."CRITERION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BC" FOREIGN KEY("FILTER_ID") REFERENCES "PUBLIC"."FILTER"("ID") NOCHECK;  
